name: openood
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.17
  - scikit-learn=0.24.2
  - scipy=1.10.1
  - json5=0.9.6
  - matplotlib=3.3.0
  - tqdm=4.62.3
  - pip
  - pip:
    - pyyaml==5.4.1
    - pre-commit
    - opencv-python==4.4.0.46
    - imgaug==0.4.0
    - pandas==1.4.1
    - diffdist==0.1
    - torchlars==0.1.2
    - mmcv==1.4.2
    - mmcls==0.17.0
    - faiss-gpu==1.7.2
    - gdown==4.5.1
    - torch==2.0.0+cu118
    - torchlars==0.1.2
    - torchmetrics==1.2.0
    - torchvision==0.15.0+cu118

