postprocessor:
  name: mos
  APS_mode: False
  postprocessor_args:
    coreset_sampling_ratio: 0.01

trainer:
  name: mos
  # group_config: /home/gmr/ood/OpenOOD/taxonomy_level0.npy
  group_config: Auto # if set to none the program will auto re-compute it
  # group_config is a list that the num of classes in each super classes
  # It should be noted that the configuration of automatic calculation may be inconsistent with
  # the category classification used in training, resulting in errors